"""``rl import smartir``: the SmartIR codes database, imported under SPEC R19.

DESIGN.md section 15 is the contract. v1 imports two of SmartIR's four
categories -- ``media_player`` and ``fan``, both genuinely button-shaped --
and, within those, only ``Broadlink``-controller profiles (D41): a
``Base64`` command is a Broadlink IR packet, decoded to a ``raw`` form
(:mod:`.broadlink`); a ``Pronto`` command is passed through verbatim as a
``pronto`` form. ``climate`` and ``light`` (state matrices, not buttons)
and every other controller/encoding are skipped and reported, never
silently dropped (R19 condition 5).

Every form is ``plausible`` and cites its upstream file and command path
(D44). Output is a pure function of the checkout and its commit, so
re-running reproduces it byte for byte (D45).
"""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..fmt import format_document
from ..import_common import authored_names as _authored_names
from ..import_common import form_compiles
from ..pronto import ProntoParseError, _word_to_hz, parse_words
from ..serialize import dumps
from .broadlink import BroadlinkDecodeError, decode_packet
from .codes import Command, Profile, SmartIrParseError, parse_profile

UPSTREAM = "smartir"
UPSTREAM_URL = "github.com/smartHomeHub/SmartIR"
IMPORT_ROOT = "remotes/smartir"
REPORT = "IMPORT.md"
TIER = "plausible"
#: v1 scope (D41): button-shaped categories, Broadlink-decodable encodings.
CATEGORIES = ("media_player", "fan")
ENCODINGS = ("Base64", "Pronto")
#: A Broadlink capture is protocol-blind: no carrier, no repeat count (D42).
DEFAULT_CARRIER_HZ = 38_000
DEFAULT_MIN_SENDS = 1
#: remote.schema.json's bound on a Pronto hex string's shape.
_PRONTO_GROUP = re.compile(r"^[0-9A-Fa-f]{4}([ \t\n]+[0-9A-Fa-f]{4})+$")
_SLUG = re.compile(r"[^A-Za-z0-9._+-]")
_ILLEGAL = re.compile(r"[^A-Za-z0-9]+")


def slug(text: str) -> str:
    return _SLUG.sub("_", text) or "_"


def key_name(path: tuple[str, ...]) -> str:
    """A command path, e.g. ``("sources", "HDMI Side")``, as one CSS
    identifier: each part upper-cased, non-identifier characters folded to
    ``_``, joined and ``KEY_``-prefixed -- mechanical, not a guess at the
    button's canonical name. (camelCase is left alone, not split: SmartIR's
    ``volumeUp`` becomes ``KEY_VOLUMEUP``, matching how the rest of the
    corpus already spells that button.)"""
    parts = []
    for part in path:
        part = _ILLEGAL.sub("_", part).strip("_")
        if part:
            parts.append(part.upper())
    return "KEY_" + "_".join(parts) if parts else "KEY_"


def _path_text(path: tuple[str, ...]) -> str:
    return ".".join(path)


@dataclass
class Report:
    commit: str
    files: Counter = field(default_factory=Counter)
    remotes: Counter = field(default_factory=Counter)
    keys: Counter = field(default_factory=Counter)
    #: (upstream file, reason) for files that yield nothing.
    skipped_files: list[tuple[str, str]] = field(default_factory=list)
    #: (upstream file, command path, reason) for commands that yield nothing.
    skipped_keys: list[tuple[str, str, str]] = field(default_factory=list)
    #: (upstream file, target path) for authored-data collisions.
    collisions: list[tuple[str, str]] = field(default_factory=list)

    def render(self) -> str:
        out = [
            "# SmartIR import report",
            "",
            "Generated by `rl import smartir` (DESIGN.md section 15); never",
            "hand-edited.",
            f"Upstream: `{UPSTREAM_URL}` @ `{self.commit}`.",
            "",
            "v1 imports the `media_player` and `fan` categories, `Broadlink`",
            "controller only (D41). Everything else upstream holds --",
            "`climate`, `light`, every other controller -- is listed here",
            "with its reason, not dropped silently (SPEC R19, condition 5).",
            "",
            "## Totals",
            "",
            "| | Count |",
            "|---|---|",
        ]
        for label, counter in (("Upstream files", self.files),
                               ("Remotes", self.remotes),
                               ("Buttons", self.keys)):
            for what, n in sorted(counter.items()):
                out.append(f"| {label}: {what} | {n:,} |")
        sections = (
            ("Files that yield no remote", ["File", "Reason"],
             sorted(self.skipped_files)),
            ("Remotes skipped because an authored remote wins (R19, condition 4)",
             ["File", "Would have been"], sorted(self.collisions)),
            ("Buttons skipped", ["File", "Command", "Reason"],
             sorted(self.skipped_keys)),
        )
        for title, header, rows in sections:
            out += ["", f"## {title} ({len(rows):,})", ""]
            if not rows:
                out.append("None.")
                continue
            out.append("| " + " | ".join(header) + " |")
            out.append("|" + "---|" * len(header))
            for row in rows:
                out.append("| " + " | ".join(_md(v) for v in row) + " |")
        return "\n".join(out) + "\n"


def _md(value: Any) -> str:
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return f"`{text}`" if text and not text[0].isdigit() else text


def _citation(where: str, command: Command, profile: Profile, how: str,
              notes: list[str]) -> str:
    """D44's fixed shape."""
    text = (f"{UPSTREAM}@{{sha}} {where}#{_path_text(command.path)} "
            f"(SmartIR profile {profile.profile_id}, {profile.manufacturer}): {how}")
    extra = [n for n in notes if n]
    if extra:
        text += "; " + "; ".join(extra)
    return text


def _pronto_carrier_hz(profile: Profile) -> int:
    """The carrier a Pronto-encoded profile's own hex declares (D42).

    Unlike a Broadlink ``Base64`` capture, a Pronto string carries its
    carrier as word 1 -- so it is read, not defaulted. R3 allows exactly
    one protocol per file; if a later command's word disagrees, that
    command fails ``pronto.decode``'s own carrier check and is reported
    like any other non-compiling button, not specially handled here. The
    first command that parses wins; if none does, :func:`import_command`
    reports each on its own terms and the file yields no keys.
    """
    for command in profile.commands:
        try:
            words = parse_words(command.code.strip())
            return _word_to_hz(words[1])
        except (ProntoParseError, IndexError):
            continue
    return DEFAULT_CARRIER_HZ


def import_command(
    command: Command, profile: Profile, upstream: str,
    protocol: dict[str, Any], report: Report,
) -> dict[str, Any] | None:
    """One key's spec, or None if the command yields nothing."""
    notes = [f"minSends: defaulted {DEFAULT_MIN_SENDS}, SmartIR does not record a repeat count"]
    if command.alternates > 1:
        notes.append(f"first of {command.alternates} upstream captures for this command")

    def skip(reason: str) -> None:
        report.keys[f"skipped: {reason}"] += 1
        report.skipped_keys.append((upstream, _path_text(command.path), reason))

    if profile.encoding == "Pronto":
        text = command.code.strip()
        if not _PRONTO_GROUP.match(text):
            skip("does not look like Pronto Hex (space-separated 4-hex groups)")
            return None
        form: dict[str, Any] = {"id": "primary.pronto", "type": "pronto", "hex": text}
        how = "broadlink pronto capture, upstream-provided verbatim"
    else:
        try:
            durations = decode_packet(command.code)
        except BroadlinkDecodeError as exc:
            skip(f"does not decode as a Broadlink IR packet: {exc}")
            return None
        if len(durations) % 2:
            skip("decodes to an odd number of durations, so it has no recorded "
                 "trailing gap, and this import does not invent one (D4a)")
            return None
        notes.insert(0, "carrier: defaulted 38 kHz, Broadlink captures do not record one")
        form = {"id": "primary.raw", "type": "raw", "repeat": durations}
        how = "broadlink IR packet, base64-decoded"

    form["confidence"] = TIER
    form["source"] = _citation(upstream, command, profile, how, notes)
    why = form_compiles(IMPORT_ROOT, protocol, "K", form)
    if why:
        skip(f"does not compile to Pronto: {why}")
        return None
    report.keys[f"imported: {form['type']}"] += 1
    return form


def import_profile(
    category: str, profile_id: str, doc: dict, upstream: str,
    authored: dict[tuple[str, str], str], report: Report,
) -> tuple[str, dict[str, Any]] | None:
    """(target path, document) for one profile, or None if it yields nothing."""
    try:
        profile = parse_profile(category, profile_id, doc)
    except SmartIrParseError as exc:
        report.files[f"skipped: {exc}"] += 1
        report.skipped_files.append((upstream, str(exc)))
        return None
    if profile.controller != "Broadlink":
        reason = f"controller {profile.controller!r} not decodable (Broadlink only, v1)"
        report.files[f"skipped: {reason}"] += 1
        report.skipped_files.append((upstream, reason))
        return None
    if profile.encoding not in ENCODINGS:
        reason = f"encoding {profile.encoding!r} not decodable (Base64/Pronto only, v1)"
        report.files[f"skipped: {reason}"] += 1
        report.skipped_files.append((upstream, reason))
        return None
    if not profile.commands:
        report.files["skipped: no commands"] += 1
        report.skipped_files.append((upstream, "no commands"))
        return None

    model = f"SmartIR {category} {profile_id}"
    target = f"{IMPORT_ROOT}/{slug(profile.manufacturer)}/{category}_{slug(profile_id)}.json"
    if (profile.manufacturer.casefold(), model.casefold()) in authored:
        report.remotes["skipped: an authored remote wins"] += 1
        report.collisions.append((upstream, target))
        return None

    carrier_hz = (_pronto_carrier_hz(profile) if profile.encoding == "Pronto"
                  else DEFAULT_CARRIER_HZ)
    protocol: dict[str, Any] = {"carrierHz": carrier_hz, "minSends": DEFAULT_MIN_SENDS}
    keys: dict[str, dict[str, Any]] = {}
    taken: set[str] = set()
    for command in profile.commands:
        name = key_name(command.path)
        base, n = name, 2
        while name.casefold() in taken:
            name, n = f"{base}_{n}", n + 1
        form = import_command(command, profile, upstream, protocol, report)
        if form is None:
            continue
        taken.add(name.casefold())
        keys[name] = {"forms": [form]}
    if not keys:
        report.files["skipped: no button compiles"] += 1
        report.skipped_files.append((upstream, "no button compiles"))
        return None
    report.remotes["imported"] += 1
    out_doc: dict[str, Any] = {
        "manufacturer": profile.manufacturer, "model": model, "aliases": [],
    }
    if profile.models:
        out_doc["controls"] = list(profile.models)
    out_doc["protocol"] = protocol
    out_doc["keys"] = keys
    return target, out_doc


def import_tree(checkout: Path, commit: str, authored: dict[tuple[str, str], str]):
    """Every upstream profile, as ``{repo path: document}`` plus the report."""
    sha = commit[:7]
    report = Report(commit=commit)
    out: dict[str, dict[str, Any]] = {}
    for category in sorted(p.name for p in (checkout / "codes").iterdir() if p.is_dir()):
        if category not in CATEGORIES:
            report.files[f"skipped: category out of scope ({category})"] += len(
                list((checkout / "codes" / category).glob("*.json"))
            )
            continue
        for path in sorted((checkout / "codes" / category).glob("*.json")):
            upstream = path.relative_to(checkout).as_posix()
            profile_id = path.stem
            try:
                doc = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
                report.files["skipped: not valid JSON"] += 1
                report.skipped_files.append((upstream, f"not valid JSON: {exc}"))
                continue
            result = import_profile(category, profile_id, doc, upstream, authored, report)
            if result is None:
                continue
            target, profile_doc = result
            for spec in profile_doc["keys"].values():
                for form in spec["forms"]:
                    form["source"] = form["source"].replace("{sha}", sha)
                    if "claims" in form:
                        for claim in form["claims"].values():
                            claim["source"] = claim["source"].replace("{sha}", sha)
            out[target] = profile_doc
    return out, report


def write_import(root: Path, checkout: Path, commit: str) -> Report:
    """Rewrite ``remotes/smartir/`` wholesale (D45): every ``*.json`` and
    ``IMPORT.md`` are the importer's; anything else there (``README.md``,
    ``LICENSE``) is authored and left alone."""
    docs, report = import_tree(checkout, commit, _authored_names(root, IMPORT_ROOT))
    target_root = root / IMPORT_ROOT
    for stale in sorted(target_root.rglob("*.json")) if target_root.exists() else []:
        if stale.relative_to(root).as_posix() not in docs:
            stale.unlink()
    for rel, doc in sorted(docs.items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(dumps(doc, sort_keys=False), encoding="utf-8", newline="\n")
        text = format_document(path)
        path.write_text(text, encoding="utf-8", newline="\n")
    target_root.mkdir(parents=True, exist_ok=True)
    (target_root / REPORT).write_text(report.render(), encoding="utf-8", newline="\n")
    for empty in sorted((p for p in target_root.rglob("*") if p.is_dir()), reverse=True):
        if not any(empty.iterdir()):
            empty.rmdir()
    return report
