"""``rl import jp1``: the JP1 device upgrades of hifi-remote.com's forum, imported under R19.

DESIGN.md section 28 is the contract. The source is ``github.com/hifiremote/deviceupgrades``,
the files of the forum's JP1 File Section, Device Upgrades: for each model of a device,
what a person programmed into a JP1 universal remote so that it sends that device's codes.
A file names its device (``Description``), a JP1 executor (``Protocol.name``) with its
device parameters, and each function's OBC byte.

Only the executors whose translators are known and checked are read (:mod:`.rmdu`): the
NEC family and Sony. Every other upgrade is listed in the report by executor, with a count,
not dropped. A file becomes one remote file per ledger protocol it uses (a Sony 12/15
upgrade may send both frames), every function a key with an ``irp`` form, Plausible, citing
the repository's commit and the file's path. Brand and category come from the forum's own
master index (``jp1-master.xls``), converted once to ``sources/jp1-device-upgrades`` by
``tools/jp1_master_to_csv.py``.
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..errors import ValidationError
from ..fmt import format_document
from ..import_common import authored_names as _authored_names
from ..import_common import form_compiles
from ..irblaster.importer import PROTOCOL_EXTRAS, fold_label
from ..protocols import REGISTRY
from ..serialize import dumps
from . import rmdu

UPSTREAM = "jp1-device-upgrades"
UPSTREAM_URL = "https://github.com/hifiremote/deviceupgrades"
IMPORT_ROOT = "remotes/jp1"
REPORT = "IMPORT.md"
#: The file of the checkout the CLI insists is unmodified (the master index is read from it).
INPUT = "jp1-master.xls"
#: Where the index, as CSV, and what it was made from are kept, relative to the repository.
MASTER_DIR = "sources/jp1-device-upgrades"
MASTER_CSV = "jp1-master.csv"
MASTER_META = "MASTER.json"
TIER = "plausible"
#: A sent frame repeats: Sony's three times (as RMT-B118P's file has it), the NEC family's once.
MIN_SENDS = {"Sony12": 3, "Sony15": 3, "Sony20": 3}
DEFAULT_MIN_SENDS = 1
#: A description that says nothing about the device.
_GENERIC = {"learned signal upgrade", "learned signals", "upgrade", "device upgrade"}
_SLUG = re.compile(r"[^A-Za-z0-9._+-]")
_SPACE = re.compile(r"[\s_]+")


def slug(text: str) -> str:
    return _SLUG.sub("_", text.strip()).strip("_.") or "_"


def norm(text: str) -> str:
    """A name as the index and the files may spell it differently: case and the space or
    underscore between words do not matter."""
    return _SPACE.sub(" ", text).strip().casefold()


@dataclass
class Report:
    commit: str
    files: Counter = field(default_factory=Counter)
    remotes: Counter = field(default_factory=Counter)
    keys: Counter = field(default_factory=Counter)
    #: Protocol name -> files, for the upgrades this import does not read.
    unread: Counter = field(default_factory=Counter)
    #: (path, reason) for upgrades of a read executor that yield nothing.
    skipped_files: list[tuple[str, str]] = field(default_factory=list)
    #: (path, function, reason) for functions that yield nothing.
    skipped_keys: list[tuple[str, str, str]] = field(default_factory=list)
    #: (path, target) for authored-data collisions.
    collisions: list[tuple[str, str]] = field(default_factory=list)
    #: ledger protocol -> files
    protocols: Counter = field(default_factory=Counter)
    brands_from: Counter = field(default_factory=Counter)

    def render(self) -> str:
        out = [
            "# JP1 device upgrades import report",
            "",
            "Generated by `rl import jp1` (DESIGN.md section 28); never hand-edited.",
            f"Upstream: `{UPSTREAM_URL}` @ `{self.commit}`.",
            "",
            "Only the executors whose translators were checked against the ledger are read (NEC1,",
            "NEC1 (No Repeats), NEC2, NECx1, NECx2, Sony 12/15, Sony20). Every other upgrade is",
            "counted under its executor below, with the KeymapMaster `.txt` files, not dropped",
            "silently (SPEC R19, condition 5).",
            "",
            "## Totals",
            "",
            "| | Count |",
            "|---|---|",
        ]
        for label, counter in (("Upstream files", self.files), ("Remotes", self.remotes),
                               ("Keys", self.keys), ("Files by ledger protocol", self.protocols),
                               ("Brand taken from", self.brands_from)):
            for what, n in sorted(counter.items()):
                out.append(f"| {label}: {what} | {n:,} |")
        sections = (
            ("Executors this import does not read (upgrades)", ["Executor", "Files"],
             sorted(self.unread.items(), key=lambda kv: (-kv[1], kv[0]))),
            ("Upgrades of a read executor that yield nothing", ["File", "Reason"],
             sorted(self.skipped_files)),
            ("Remotes skipped because an authored remote wins (R19, condition 4)",
             ["File", "Would have been"], sorted(self.collisions)),
            ("Functions skipped", ["File", "Function", "Reason"], sorted(self.skipped_keys)),
        )
        for title, header, rows in sections:
            out += ["", f"## {title} ({len(rows):,})", ""]
            if not rows:
                out.append("None.")
                continue
            out.append("| " + " | ".join(header) + " |")
            out.append("|" + "---|" * len(header))
            for row in rows:
                out.append("| " + " | ".join(_md(v) for v in row) + " |")
        return "\n".join(out) + "\n"


def _md(value: Any) -> str:
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return f"`{text}`" if text and not text[0].isdigit() else text


# --- the master index ---------------------------------------------------------------------


@dataclass
class Master:
    by_name: dict[str, list[dict[str, str]]]
    brands: list[str]
    #: A brand as the index mostly spells it, by its case-folded form (`SONY` and `Sony` are one).
    spelling: dict[str, str]

    def brand(self, text: str) -> str:
        return self.spelling.get(norm(text), text.strip())


def load_master(root: Path, checkout: Path, commit: str) -> Master:
    """The index as CSV, after checking it is the one of this checkout: the same commit and
    the same ``jp1-master.xls`` bytes."""
    directory = root / MASTER_DIR
    try:
        meta = json.loads((directory / MASTER_META).read_text(encoding="utf-8"))
        rows = list(csv.DictReader((directory / MASTER_CSV).read_text(encoding="utf-8").splitlines()))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValidationError(f"{directory}: cannot read the master index: {exc}; "
                              "run tools/jp1_master_to_csv.py") from exc
    if not commit.startswith(meta["commit"][:7]) and not meta["commit"].startswith(commit[:7]):
        raise ValidationError(f"{directory / MASTER_CSV} was made from commit {meta['commit'][:7]}, "
                              f"the checkout is at {commit[:7]}; run tools/jp1_master_to_csv.py")
    xls = checkout / INPUT
    if xls.is_file() and hashlib.sha256(xls.read_bytes()).hexdigest() != meta["xlsSha256"]:
        raise ValidationError(f"{xls} is not the workbook {MASTER_CSV} was made from; "
                              "run tools/jp1_master_to_csv.py")
    by_name: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_name[norm(Path(row["File Name"]).stem)].append(row)
    counts: dict[str, Counter] = defaultdict(Counter)
    for row in rows:
        if row["Brand"].strip():
            counts[norm(row["Brand"])][row["Brand"].strip()] += 1
    # the commonest spelling, and the first in the alphabet among equals: not the order of a set
    spelling = {key: sorted(c.items(), key=lambda kv: (-kv[1], kv[0]))[0][0] for key, c in counts.items()}
    brands = sorted(spelling.values(), key=lambda b: (-len(b), b))
    return Master(by_name, brands, spelling)


def master_row(master: Master, rel: Path) -> dict[str, str] | None:
    """The index row of an upgrade: by file name, and where several rows share one, by the
    category the repository files it under."""
    rows = master.by_name.get(norm(rel.stem), [])
    if len(rows) > 1:
        same = [r for r in rows if norm(r["Category"]) == norm(rel.parts[0])]
        rows = same if same else rows
    return rows[0] if len(rows) == 1 else None


def brand_by_prefix(master: Master, text: str) -> str | None:
    """The longest brand of the index that begins ``text``, at a word."""
    t = norm(text)
    for brand in master.brands:
        b = norm(brand)
        if t == b or t.startswith(b + " "):
            return brand
    return None


def split_model(brand: str, description: str) -> str:
    """The description without the brand it begins with."""
    d, b = description.strip(), norm(brand)
    if norm(d).startswith(b + " "):
        rest = d[len(brand):].strip(" -:,")
        if rest:
            return rest
    return d


# --- names -------------------------------------------------------------------------------


def key_names(members: list[tuple[int, str | None]]) -> dict[int, str]:
    """``{function index: key name}``: ``KEY_<folded name>``; where two functions fold alike,
    or a name folds to nothing or is missing, every one of them gets ``_<index>``."""
    base = {i: "KEY_" + (fold_label(label or "") or "FUNCTION") for i, label in members}
    carriers: dict[str, list[int]] = defaultdict(list)
    for i, name in base.items():
        carriers[name].append(i)
    return {i: (f"{name}_{i}" if len(carriers[name]) > 1 or name == "KEY_FUNCTION" else name)
            for i, name in base.items()}


def signal_text(signal: rmdu.Signal) -> str:
    out = f"{signal.protocol} device {signal.device}"
    if signal.subdevice is not None:
        out += f" subdevice {signal.subdevice}"
    return out + f" function {signal.function}"


class Importer:
    def __init__(self, sha: str, master: Master, authored: dict[tuple[str, str], str], report: Report):
        self.sha, self.master, self.authored, self.report = sha, master, authored, report
        self._compiles: dict[tuple, str | None] = {}
        self._models: dict[tuple[str, str], str] = {}

    def gate(self, signal: rmdu.Signal) -> str | None:
        key = (signal.protocol, signal.device, signal.subdevice, signal.function)
        if key not in self._compiles:
            form: dict[str, Any] = {"id": "primary.irp", "type": "irp", "device": signal.device,
                                    "function": signal.function, "confidence": TIER, "source": "probe"}
            if signal.subdevice is not None:
                form["subdevice"] = signal.subdevice
            probe_block = {k: v for k, v in self.block(signal.protocol).items() if k != "claims"}
            self._compiles[key] = form_compiles(IMPORT_ROOT, probe_block, "K", form)
        return self._compiles[key]

    @staticmethod
    def block(protocol: str) -> dict[str, Any]:
        """What a remote file's ``protocol`` carries: the IR Blaster import's own extras (Samsung36's unit of
        500 us, D65) apply here too, so one code compiles to one signal whichever source it came from."""
        block: dict[str, Any] = {"name": protocol, "carrierHz": REGISTRY[protocol].nominal_carrier_hz,
                                 "minSends": MIN_SENDS.get(protocol, DEFAULT_MIN_SENDS)}
        block.update(PROTOCOL_EXTRAS.get(protocol, {}))
        return block

    def names_of(self, upgrade: rmdu.Upgrade, rel: Path) -> tuple[str, str, str] | None:
        """``(brand, model, description)`` of an upgrade, or None (reported) when it has no brand."""
        report = self.report
        row = master_row(self.master, rel)
        description = upgrade.fields.get("Description", "").strip()
        if not description or description.casefold() in _GENERIC:
            description = (row["File Description (from web)"].strip() if row else "") or rel.stem
        brand = self.master.brand(row["Brand"]) if row and row["Brand"].strip() else ""
        if brand:
            report.brands_from["the master index"] += 1
        else:
            brand = brand_by_prefix(self.master, description) or brand_by_prefix(self.master, rel.stem) or ""
            if brand:
                report.brands_from["the longest brand of the index that begins the description"] += 1
        if not brand:
            report.files["skipped: no brand"] += 1
            report.skipped_files.append((rel.as_posix(), "no brand: the file is not in the master index "
                                         "and its description begins with no brand of it"))
            return None
        return brand, split_model(brand, description), description

    def import_file(self, rel: Path, upgrade: rmdu.Upgrade) -> list[tuple[str, dict[str, Any]]]:
        report = self.report
        where = rel.as_posix()
        decoded: dict[str, list[tuple[rmdu.Function, rmdu.Signal]]] = defaultdict(list)
        for function in upgrade.functions:
            result = rmdu.signal_of(upgrade, function)
            label = function.name or f"#{function.index}"
            if isinstance(result, str):
                report.keys[f"skipped: {result}"] += 1
                report.skipped_keys.append((where, label, result))
                continue
            why = self.gate(result)
            if why:
                reason = f"does not compile to Pronto: {why}"
                report.keys[f"skipped: {reason}"] += 1
                report.skipped_keys.append((where, label, reason))
                continue
            decoded[result.protocol].append((function, result))
        if not decoded:
            report.files["skipped: no function decodes"] += 1
            report.skipped_files.append((where, "no function decodes"))
            return []
        names = self.names_of(upgrade, rel)
        if names is None:
            return []
        brand, model, description = names
        out = []
        for protocol in sorted(decoded):
            suffix = f" [{protocol}]" if len(decoded) > 1 else ""
            full = f"{model}{suffix}"
            taken = self._models.get((brand.casefold(), full.casefold()))
            if taken is not None:
                full = f"{model} ({rel.stem}){suffix}"
            target = (f"{IMPORT_ROOT}/{slug(brand)}/{slug(rel.parts[0])}-{slug(rel.stem)}"
                      f"{('-' + protocol.lower()) if len(decoded) > 1 else ''}.json")
            if (brand.casefold(), full.casefold()) in self.authored:
                report.remotes["skipped: an authored remote wins"] += 1
                report.collisions.append((where, target))
                continue
            self._models[(brand.casefold(), full.casefold())] = target
            out.append((target, self.document(rel, upgrade, brand, full, description, protocol,
                                              decoded[protocol])))
        return out

    def document(self, rel: Path, upgrade: rmdu.Upgrade, brand: str, model: str, description: str,
                 protocol: str, members: list[tuple[rmdu.Function, rmdu.Signal]]) -> dict[str, Any]:
        report = self.report
        names = key_names([(f.index, f.name) for f, _s in members])
        keys: dict[str, dict[str, Any]] = {}
        for function, signal in members:
            form: dict[str, Any] = {"id": "primary.irp", "type": "irp", "device": signal.device}
            if signal.subdevice is not None:
                form["subdevice"] = signal.subdevice
            form["function"] = signal.function
            form["confidence"] = TIER
            source = (f"{UPSTREAM}@{self.sha} {rel.as_posix()} function {function.index} "
                      f"'{function.name or ''}' (OBC {function.hex.upper()}; {upgrade.protocol_name}, "
                      f"parms {' '.join(upgrade.parms) or 'none'}): {signal_text(signal)}")
            if function.notes:
                source += f"; the upgrade's note: '{function.notes}'"
            form["source"] = source
            spec: dict[str, Any] = {}
            if function.name:
                spec["label"] = function.name
            spec["forms"] = [form]
            keys[names[function.index]] = spec
            report.keys[f"imported: {protocol}"] += 1
        report.remotes["imported"] += 1
        report.protocols[protocol] += 1
        return {"manufacturer": brand, "model": model, "aliases": [], "controls": [description],
                "protocol": self.block(protocol), "keys": keys}


# --- the whole checkout ---------------------------------------------------------------------


def import_tree(root: Path, checkout: Path, commit: str, authored: dict[tuple[str, str], str]):
    """Every file the checkout yields, as ``{repo path: document}``, plus the report."""
    sha = commit[:7]
    report = Report(commit=commit)
    master = load_master(root, checkout, commit)
    importer = Importer(sha, master, authored, report)
    out: dict[str, dict[str, Any]] = {}
    for path in sorted(checkout.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(checkout)
        if ".git" in rel.parts or len(rel.parts) < 2:
            continue
        suffix = path.suffix.lower()
        if suffix == ".txt":
            report.files["not read: KeymapMaster .txt"] += 1
            continue
        if suffix != ".rmdu":
            continue
        report.files["upgrades"] += 1
        upgrade = rmdu.parse(rmdu.decode_text(path.read_bytes()))
        if upgrade.protocol_name not in rmdu.MAPPED:
            report.unread[upgrade.protocol_name or "(none)"] += 1
            continue
        if not upgrade.functions:
            report.files["skipped: no functions"] += 1
            report.skipped_files.append((rel.as_posix(), "no functions"))
            continue
        for target, doc in importer.import_file(rel, upgrade):
            # two files of one category whose names differ only in spaces or underscores slug
            # alike; the path order, which is the order here, numbers the second
            base, n = target.removesuffix(".json"), 2
            while target in out:
                target, n = f"{base}-{n}.json", n + 1
            out[target] = doc
    return out, report


def write_import(root: Path, checkout: Path, commit: str) -> Report:
    """Rewrite ``remotes/jp1/`` wholesale: every ``*.json`` and ``IMPORT.md`` are the
    importer's; anything else there (``README.md``) is authored and left alone."""
    docs, report = import_tree(root, checkout, commit, _authored_names(root, IMPORT_ROOT))
    target_root = root / IMPORT_ROOT
    for stale in sorted(target_root.rglob("*.json")) if target_root.exists() else []:
        if stale.relative_to(root).as_posix() not in docs:
            stale.unlink()
    for rel, doc in sorted(docs.items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(dumps(doc, sort_keys=False), encoding="utf-8", newline="\n")
        path.write_text(format_document(path), encoding="utf-8", newline="\n")
    target_root.mkdir(parents=True, exist_ok=True)
    (target_root / REPORT).write_text(report.render(), encoding="utf-8", newline="\n")
    for empty in sorted((p for p in target_root.rglob("*") if p.is_dir()), reverse=True):
        if not any(empty.iterdir()):
            empty.rmdir()
    return report
