"""What every maker's reader shares: the snapshot, the report, and the shape of a file.

A maker's documents are kept in ``sources/official/<maker>/`` as the server sent them, with the
sheets the importer reads converted to CSV by ``tools/official_sheets_to_csv.py``, and a
``MANIFEST.json`` that names each document's URL, size and SHA-256 and each CSV's source and
SHA-256. Nothing is read that the manifest does not vouch for (D123).
"""

from __future__ import annotations

import csv
import hashlib
import json
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..errors import ValidationError

IMPORT_ROOT = "remotes/official"
SNAPSHOT = "sources/official"
MANIFEST = "MANIFEST.json"
REPORT = "IMPORT.md"
TIER = "plausible"
DOUBTFUL_TIER = "untested"


@dataclass
class Snapshot:
    maker: str
    retrieved: str
    directory: Path
    documents: dict[str, dict[str, Any]]
    sheets: dict[str, dict[str, Any]]

    def sha(self, document: str) -> str:
        return self.documents[document]["sha256"][:8]

    def sheet_of(self, document: str, sheet: str) -> list[list[str]]:
        for name, entry in self.sheets.items():
            if entry["document"] == document and entry["sheet"] == sheet:
                with (self.directory / "csv" / name).open(encoding="utf-8", newline="") as handle:
                    return [row for row in csv.reader(handle)]
        raise ValidationError(f"{self.directory}: the manifest has no CSV of sheet {sheet!r} of {document}")


def load_snapshot(directory: Path) -> Snapshot:
    """One maker's snapshot, every document and CSV checked against the manifest."""
    path = directory / MANIFEST
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValidationError(f"{path}: cannot read the snapshot manifest: {exc}") from exc
    for name, entry in manifest["documents"].items():
        _verify(directory / name, entry["sha256"])
    for name, entry in manifest["sheets"].items():
        _verify(directory / "csv" / name, entry["sha256"])
    return Snapshot(manifest["maker"], manifest["retrieved"], directory, manifest["documents"], manifest["sheets"])


def _verify(path: Path, sha256: str) -> None:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise ValidationError(f"{path}: listed in the manifest but unreadable: {exc}") from exc
    if hashlib.sha256(data).hexdigest() != sha256:
        raise ValidationError(f"{path} is not the file the manifest pins (SHA-256 differs); run "
                              "tools/fetch_official.py and tools/official_sheets_to_csv.py again to re-pin")


@dataclass
class Report:
    #: maker -> Counter of what was read and written
    counts: dict[str, Counter] = field(default_factory=dict)
    #: (maker, document, reason) -> rows
    unrepresented: Counter = field(default_factory=Counter)
    #: (maker, where, reason) for anything the maker's reader refuses or doubts
    notes: list[tuple[str, str, str]] = field(default_factory=list)
    collisions: list[tuple[str, str]] = field(default_factory=list)
    retrieved: dict[str, str] = field(default_factory=dict)

    def count(self, maker: str, what: str, n: int = 1) -> None:
        self.counts.setdefault(maker, Counter())[what] += n

    @property
    def remotes(self) -> int:
        return sum(c["files"] for c in self.counts.values())

    @property
    def keys(self) -> int:
        return sum(c["keys"] for c in self.counts.values())

    def render(self) -> str:
        out = [
            "# Manufacturers' own IR tables, import report",
            "",
            "Generated by `rl import official` (DESIGN.md section 29); never hand-edited.",
            "Each maker's documents are pinned in `sources/official/<maker>/` with their URL, SHA-256",
            "and retrieval date (" + ", ".join(f"{m} {d}" for m, d in sorted(self.retrieved.items())) + ").",
            "",
            "Everything a document holds that does not become a key is listed here with its reason, not",
            "dropped silently (SPEC R19, condition 5).",
            "",
            "## Totals",
            "",
            "| | Count |",
            "|---|---|",
        ]
        for maker in sorted(self.counts):
            for what, n in sorted(self.counts[maker].items()):
                out.append(f"| {maker}: {what} | {n:,} |")
        for title, header, rows in (
            ("Rows that become no key", ["Maker", "Document", "Reason", "Rows"],
             [(m, d, r, n) for (m, d, r), n in sorted(self.unrepresented.items())]),
            ("Notes on what a document says", ["Maker", "Where", "Note"], sorted(self.notes)),
            ("Files skipped because an authored remote wins (R19, condition 4)", ["Maker", "Would have been"],
             sorted(self.collisions)),
        ):
            out += ["", f"## {title} ({len(rows):,})", ""]
            if not rows:
                out.append("None.")
                continue
            out.append("| " + " | ".join(header) + " |")
            out.append("|" + "---|" * len(header))
            for row in rows:
                out.append("| " + " | ".join(_md(v) for v in row) + " |")
        return "\n".join(out) + "\n"


def _md(value: Any) -> str:
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return f"`{text}`" if text and not text[0].isdigit() else text


def slug(text: str) -> str:
    import re
    return re.sub(r"[^A-Za-z0-9._+-]", "_", text.strip()).strip("_.") or "_"
